#ifndef _TOKENCODES_H_
#define _TOKENCODES_H_

enum { ID, CT_INT, CT_REAL, CT_CHAR, CT_STRING, END, BREAK, CHAR, DOUBLE, ELSE, FOR, IF, INT, RETURN, STRUCT, VOID, WHILE, COMMA, SEMICOLON, LPAR, RPAR, LBRACKET, RBRACKET, LACC, RACC, ADD, SUB, MUL, DIV, DOT, AND, OR, NOT ,ASSIGN, EQUAL, NOTEQ, LESS, LESSEQ, GREATER, GREATEREQ, LINECOMMENT, COMMENT };

#endif